#!/bin/bash

set -eu

Rscript -e "source('http://bioconductor.org/biocLite.R'); biocLite(ask=FALSE); biocLite(c('ballgown', 'CAGEr', 'ShortRead', 'Rsamtools', 'GenomicAlignments', 'GenomicFeatures', 'Biostrings', 'BSgenome', 'ggbio', 'seqLogo', 'GenomicRanges', 'BiocStyle', 'ChIPseeker', 'msa', 'Gviz', 'topGO', 'qvalue'), ask=FALSE)"

exit
