#!/bin/bash

set -eu

Rscript -e "source('http://bioconductor.org/biocLite.R'); biocLite(ask=FALSE); biocLite(c('ballgown', 'CAGEr', 'ShortRead', 'Rsamtools', 'GenomicAlignments', 'GenomicFeatures', 'Biostrings', 'BSgenome', 'ggbio', 'GenomicRanges', 'BiocStyle', 'ChIPseeker', 'msa', 'Gviz', 'topGO', 'qvalue', 'org.Pf.plasmo.db', 'Rsubread', 'limma', 'edgeR', 'DESeq2', 'rtracklayer'), ask=FALSE)"

exit
